import { createSlug } from "~/utils";
import {
  InsertRecipeIngredientSchema,
  InsertRecipeStepSchema,
} from "~/db/schema/recipe.server";
import {
  createRecipe,
  createRecipeIngredients,
  createRecipeSteps,
} from "~/models/recipe.server";

(async () => {
  const recipesData = [
    {
      title: "Soft Snickerdoodle Cookies",
      description: "",
      ingredients: [
        "1 cup butter",
        "11/2 cups sugar",
        "2 large eggs",
        "2 3/4 cups flour",
        "2 tsp cream of tartar",
        "1 tsp baking soda",
        "1/4 tsp salt",
        "3 TB sugar",
        "3 tsp cinnamon",
      ],
      steps: [
        "Preheat oven to 350\u00b0F",
        "Mix butter, 1 1/2 cups sugar and eggs thoroughly in a large bowl.",
        "Combine flour, cream of tartar, baking soda and salt in a separate bowl.",
        "Blend dry ingredients into butter mixture",
        "Chill dough, and chill an ungreased cookie sheet for about",
        "10-15 minutes in the fridge.",
        "Meanwhile, mix 3 tablespoons sugar, and 3 teaspoons cinnamon in a small bowl.",
        "Scoop 1 inch globs of dough into the sugar/ cinnamon mixture.",
        "Coat by gently rolling balls of dough in the sugar mixture.",
        "Place on chilled ungreased cookie sheet, and bake 10 minutes.",
        "Remove from pan immediately.",
      ],
      createdAt: "2023-07-26T23:12:54.395480",
      updatedAt: "2023-07-26T23:12:54.395488",
    },
    {
      title: "Mocha Icing",
      description:
        "This only makes about 1 cup, enough for 16 cupcakes. Have everything measured before you begin. Heating will produce a creamier and more intense flavor, but you must carefully heat this up in double broiler. Barely let the water simmer. If the mixture gets too hot, it will turn out grainy.",
      ingredients: [
        "2 TB unsweetened cocoa",
        "1 ts instant coffee",
        "1 \u00bd TB water",
        "1/8 ts salt",
        "1 ts vanilla",
      ],
      steps: [
        "Melt the butter in double broiler, then remove from heat. Stir in all ingredients except vanilla. Cook, over barely simmering water for about 5 minutes.",
        "Remove from heat and add vanilla.",
        "Beat until cool and desired consistency.",
        "To store, cover surface with plastic wrap. Keeps 3 days at room temperature, 3 weeks in fridge or can freeze up to 6 months.",
      ],
      createdAt: "2023-07-26T23:12:54.395490",
      updatedAt: "2023-07-26T23:12:54.395492",
    },
    {
      title: "Pasta with Broccoli and Sausage",
      description:
        "Double Batch: double ingredients except where indicted below in ()",
      ingredients: [
        "1 head broccoli, cut into florets",
        "1 9 oz pkg Buitoni refrigerated fettuccine, slice entire pkg in 3 pieces",
        "2 TB butter",
        "1 8 oz pkg mushrooms, sliced",
        "2 garlic cloves, minced",
        "1 lb reduced fat sausage, sliced",
        "3 large eggs\t\t\t\t\t(4 eggs)",
        "\u00be cup whipping cream\t\t\t(1 cup whipping cream)",
        "\u00be ts pepper, salt and Cholula to taste",
        "1 cup grated parmesan cheese",
        "-other veggies like onions, red pepper, carrots can be added to up the nutrition",
      ],
      steps: [
        "Boil big pan of water.  When water is boiling, do steps A and B at the same time:",
        "A: Add broccoli florets to boiling water for 4 minutes, then add fettuccine for 2 minutes; drain.  Keep in colander.  If you need to let it sit, you might need to add in some oil or give it a stir to keep it from sticking.",
        "B: Melt butter in a large dutch oven; add mushrooms and sausage (and any other veggies, except garlic), and saut\u00e9 5-7 minutes or until tender (adding the garlic the last minute).",
        "Add in the broccoli and fettuccine.",
        "Combine eggs, whipping cream, and spices in a bowl and then stir into pan tossing until blended.  Add in the cheese as you are tossing.  Cook over low heat, stirring constantly, 3 to 5 minutes or until thickened.  Serve immediately.",
      ],
      createdAt: "2023-07-26T23:12:54.395493",
      updatedAt: "2023-07-26T23:12:54.395494",
    },
    {
      title: "Creamy Tomato Basil Soup with Parmesan",
      description: "",
      ingredients: [
        "4 tablespoons butter",
        "1 medium onion chopped",
        "1 clove of garlic grated or finely minced",
        "1/4 cup all purpose flour",
        "32 ounces 4 cups chicken stock",
        "2 28 ounce cans whole tomatoes in juice",
        "10 basil leaves about 1/4 cup, chopped",
        "1 cup heavy cream",
        "8 ounces grated parmesan cheese about 2 cups",
        "salt and pepper",
      ],
      steps: [
        "Heat a large pot over medium heat. Melt the butter, then add the chopped onions. Add 1 teaspoon salt and 1 teaspoon pepper. Saute the onion about 8 minutes until they turn translucent, stirring occasionally. Add in the garlic and cook for 30 seconds, or until fragrant.",
        "Sprinkle in the flour, and stir to cook the flour for 1 minute. Will look like a paste. Slowly stir in the chicken stock, whisking the whole time so the flour doesn't clump. Then add the canned tomatoes and basil. You can either transfer to a slow cooker and cook over low for 4 hours or high for 2 hours, or cook it on the stove top by bringing it to a boil, then cover and reduce heat to low and cook for 20 more minutes.",
        "Remove the lid, and either use an immersion blender or stand blender (careful when blending hot liquids in a stand blender!). Blend until the soup is creamy. Then stir in the parmesan cheese and heavy cream. Heat soup for another 5-10 minutes, or until the cheese is melted and the soup is warm. Taste for salt and pepper. Serve warm.",
        "Leftovers will keep for 1 week in an airtight container. Freezes beautifully. See notes for freezing tips.",
      ],
      createdAt: "2023-07-26T23:12:54.395495",
      updatedAt: "2023-07-26T23:12:54.395496",
    },
    {
      title: "Charro Beans",
      description:
        "If using dried beans, you need to read package instructions.  2 days before you can soak them, then 1 day before, cook them.  You can also do it all in one day with a quick soak, if you start early.",
      ingredients: [
        "6 slices bacon, reserve drippings",
        "1 small white onion, chopped",
        "2 jalapenos, chopped small and seeded",
        "1 lb dried beans OR if short on time, 5 cups drained and rinsed canned pinto beans",
        "1 cup bean cooking liquid or water or chicken stock",
        "\u00bc ts dried oregano",
        "\u00bc ts smoked paprika",
        "Salt and pepper to taste",
      ],
      steps: [
        "Cook dried beans to package directions, adding \u00bd ts salt and pepper (put   in fridge if cooking the day before with the left-over cooking liquid).",
        "Cook bacon in large dutch oven and reserve drippings.  Add onion and jalapenos and cook until soft.",
        "Stir in cooked beans and 1 cup liquid, oregano and paprika.  Cook on medium low until beans are moist, but not soupy (10 minutes).  Stir in salt and pepper to taste and serve hot.",
      ],
      createdAt: "2023-07-26T23:12:54.395498",
      updatedAt: "2023-07-26T23:12:54.395499",
    },
    {
      title: "Greek Zucchini Balls",
      description: "",
      ingredients: [
        "4-5 cups grated zucchini",
        "2 teaspoons salt",
        "1 cup crumbled feta cheese preferably Greek",
        "2 large eggs, beaten",
        "3 green onions cleaned and thinly sliced",
        "1/4 cup finely chopped fresh mint",
        "2-3 shakes Chalula",
        "1/2 teaspoon black pepper",
        "1 1/2 cups approximately self-rising flour",
        "Olive oil for frying",
      ],
      steps: [
        "Wash the zucchini and cut off the ends, but do not peel. Grate with a food processor or box grater. Put the grated zucchini in a colander, sprinkle with salt, and mix to coat evenly. Place the colander in the sink and let the zucchini drain for 15-30 minutes. Gently squeeze the zucchini with your hands to remove as much water as possible.",
        "While the zucchini is draining, combine the eggs, green onion, mint, feta, and black pepper in a large bowl. Add the drained zucchini. Mix in enough self-rising flour to make a soft dough, about 1 1/2 cups.",
        "Deep fryer cooking instructions: If using a deep fryer, preheat the oil, preferably olive oil, to 375\u00b0F. Line a large plate with 3-4 layers of paper towel.",
        "Drop the dough, one tablespoon at a time, into the hot oil, trying to keep the dough in a ball shape. Fry 4 or 5 zucchini balls at a time for 2-3 minutes, until they are medium golden brown. Turn the zucchini balls with tongs as necessary evenly.",
        "Remove the zucchini balls from the hot oil with tongs, a slotted spoon or a spider strainer. Place them on the paper towel-lined plate to drain away excess oil.",
        "Stovetop cooking instructions: If cooking the zucchini balls on the stovetop, put about 1/3 inch of olive oil in the bottom of a 12-inch skillet, and heat over medium-high heat to 375\u00b0F.",
        "If you don't have a frying thermometer, you can test the temperature of the oil by dropping in a small amount of batter. The batter should start to bubble and sizzle right away, but the oil should not be smoking hot.",
        "When the oil is hot, drop tablespoons of batter into the oil. Zucchini balls will have more of a patty or fritter shape if cooked in a skillet. Cook 4-5 zucchini balls at a time, about 2 minutes on each side, until medium golden brown. Flip the zucchini balls with tongs halfway through the cooking time. Transfer to the paper towel-lined plate to cool.",
        "Serve the zucchini balls with Authentic Greek Tzatziki Sauce.",
      ],
      createdAt: "2023-07-26T23:12:54.395500",
      updatedAt: "2023-07-26T23:12:54.395501",
    },
    {
      title: "Funfetti Cake",
      description: "",
      ingredients: [
        "2\u00bd cups flour",
        "\u00bc cup cornstarch",
        "1 teaspoon kosher salt",
        "2 teaspoons baking powder",
        "1 cup unsalted butter, at room temperature",
        "1\u00bd cups sugar",
        "4 large egg whites",
        "\u00bc cup flavorless oil",
        "1 tablespoon clear imitation vanilla (I prefer McCormick brand)",
        "\u00bd teaspoon almond extract",
        "\u00be cup whole milk",
        "\u00bd cup rainbow sprinkles (artificially colored cylinder sprinkles, not nonpareils or anything naturally colored, they will bleed through the batter) I get mine from Amazon: Unpretentious Baker brand, \u2018Rainbow Sprinkles (4 Cups) Colorful Jimmies, Decorative & Fun Dessert Topping for Baking\u2019",
      ],
      steps: [
        "To make the cake: Preheat the oven to 350\u00baF. Grease and line the bottoms of three 8-inch cake pans or line 24 cups of two muffin tins.",
        "In a medium bowl, whisk together the flour, cornstarch, salt, and baking powder.",
        "In a stand mixer (or handheld) fitted with the paddle attachment, cream together the butter and sugar until light and fluffy, 3 to 4 minutes. Add the egg whites, one at a time, mixing well after each addition. Add the oil and the extracts.",
        "With the mixer running on low speed, add the dry mixture and the milk in two or three alternating batches and mix until just barely combined. Using a rubber spatula, gently fold in the sprinkles until they\u2019re evenly distributed. Distribute the batter among the cake pans or muffin cups (1/4 cup), spreading it out evenly if using cake pans.",
        "Bake until a toothpick inserted into the center comes out clean. Begin checking for doneness at 25 minutes for cakes and 17 minutes for cupcakes.",
        "Let cool in the pans for 10 minutes and then turn onto a wire rack to cool completely.",
        "Frost the cake or cupcakes as desired and enjoy. Probably not enough for thick layer on outside of cake.",
      ],
      createdAt: "2023-07-26T23:12:54.395502",
      updatedAt: "2023-07-26T23:12:54.395503",
    },
    {
      title: "Sausage-Cheese Muffins",
      description: "Makes 1 dozen.",
      ingredients: [
        "1 lb Jimmy Dean Hot Sausage",
        "3 cups all-purpose baking mix (I use Bisquick)",
        "1 \u00bd cups (6 oz) shredded Cheddar Cheese",
        "1 (10 \u00be oz) can condensed cheese soup",
        "\u00be cup water",
      ],
      steps: [
        "Cook sausage in large skillet until no longer pink. Drain and put on paper toweled lined plate.",
        "Combine sausage, baking mix, and shredded cheese in large bowl;",
        "make a well in canter of mixture.",
        "Stir together soup and \u00be cup water; add to sausage mixture, stirring just until dry ingredients are moistened. Spoon into lightly greased (I use butter flavored Crisco) muffin pans, filling to tops of cups.",
        "Bake at 375 for 20 to 25 minutes or until lightly browned.",
        "Cool in pan 10 minutes, then on cooling rack.",
      ],
      createdAt: "2023-07-26T23:12:54.395505",
      updatedAt: "2023-07-26T23:12:54.395506",
    },
    {
      title: "Greek Chicken Kebabs",
      description: "",
      ingredients: [
        "2 lbs boneless chicken, diced in 1 \u00bc cubes",
        "\u00bc cup EVOO",
        "3 TB fresh lemon juice",
        "1 TB red wine vinegar",
        "3 cloves garlic, minced",
        "2 ts dried oregano",
        "\u00bd ts dried basil",
        "\u00bd ts dried thyme",
        "\u00bd ts ground coriander",
        "\u00bd ts salt",
        "\u00bd ts pepper",
        "2 lg red peppers, diced into 1 \u00bc\u201d pieces",
        "3 small zucchini (about 1 lb), sliced into 1/3\u201d slices",
        "1 lg red onion, sliced in 1 \u201c wedges",
        "",
      ],
      steps: [
        "Mix marinade in gallon size bag, combine, add chicken and veggies.",
        "Marinade 2 hours or overnight.",
        "Put on skewers.  Grill on pre-heated grill 7-9 minutes, 165 degrees.",
        "Serve with Tzatziki Sauce.",
      ],
      createdAt: "2023-07-26T23:12:54.395507",
      updatedAt: "2023-07-26T23:12:54.395508",
    },
    {
      title: "Texas Sheet Cake or Cup Cakes",
      description: "",
      ingredients: [
        "2 cups sugar",
        "2 cups flour",
        "1 ts baking soda",
        "\u2151 ts salt",
        "1 cup water",
        "\u00bd2 cup veg. oil",
        "8 TB unsalted butter",
        "\u00bc cup unsweetened cocoa",
        "2 1g eggs, lightly beaten",
        "\u00bd cup buttermilk",
        "1 ts vanilla",
      ],
      steps: [
        "Preheat 375 degrees",
        "Sift together in a large bowl: sugar, flour, baking soda, salt",
        "Combine in a medium saucepan and bring to a boil, stirring constantly: water, veg. oil, unsalted butter, unsweetened cocoa",
        "Pour the hot mixture over dry and stir just until smooth.",
        "Whisk together then stir into batter: eggs, buttermilk, vanilla",
        "Scape batter into greased and floured 13 x 9 pan or cupcakes. Bake until toothpick comes out clean, 20 to 25 minutes for cake. Less for cupcakes.",
        "If you double it, you'll get about 3 dozen cupcakes.",
      ],
      createdAt: "2023-07-26T23:12:54.395509",
      updatedAt: "2023-07-26T23:12:54.395510",
    },
    {
      title: "Basic Yellow Cake or Cup Cake Recipe",
      description: "",
      ingredients: [
        "1 cup unsalted butter, softened",
        "2 cups sugar",
        "3 eggs",
        "3 cups sifted flour",
        "1 tablespoon baking powder",
        "1 1/4 cups milk",
        "1/2 teaspoon vanilla extract",
        "\u00bd teaspoon vanilla extract",
      ],
      steps: [
        "Cream butter then gradually add sugar, beating well.",
        "Add eggs, beating well after each addition: this mix should be fluffy yellow.",
        "In another bowl, combine the flour and baking powder: The add mix to the creamed mixture (above) alternating with milk, beginning and ending with the flour mix. Mix well.",
        "Stir in vanilla.",
        'Pour batter into 2 greased/floured 9" pans (about 3 \u00bc cups',
        "batter each). Bake at 350 degrees for 25 minutes or until a toothpick inserted in the center comes out clean.",
        "Cool in pan for 10 minutes then remove layers from pans and cool completely.",
        "If making cupcakes, fill 2/3's full, if you double recipe, you'll get at least 36 cupcakes. Bake about 24 minutes.",
      ],
      createdAt: "2023-07-26T23:12:54.395512",
      updatedAt: "2023-07-26T23:12:54.395513",
    },
    {
      title: "Stuffed Chicken in Sun Dried Tomato Cream Sauce",
      description:
        "A turkey carcass soup is the answer when you don't want to waste a single bite of turkey. This is a delicious soup and one of my favorites. If you want to freeze some, leave out the potatoes.",
      ingredients: [
        "4 large boneless chicken breasts",
        "1 TB EVOO",
        "1 tsp paprika",
        "\u00bc ts garlic powder",
        "\u00bc ts onion powder",
        "1 ts salt",
        "4 oz cream cheese (try ricotta)",
        "10 oz frozen chopped spinach, thawed and drained",
        "\u00bd ts salt",
        "\u00bd ts red pepper flakes",
        "2 TB salted butter",
        "2 cloves garlic, minced",
        "\u00bd ts red pepper flakes",
        "1 cup chicken broth",
        "\u00bd cup heavy cream",
        "\u00bd cup julienne cut sun dried tomatoes in Olive Oil",
        "\u00bc cup Parmesan cheese, grated or shredded",
        "1 \u00bd ts Italian seasoning",
      ],
      steps: [
        "Preheat oven to 375.  Pound chicken breasts to flatten.  Cut a pocket into each breast.  Drizzle chicken breasts with olive oil.  Combine ingredients 3 thru 6 and coat onto breasts pressing in with fingers, both sides. Refrigerate.",
        "Make filling.  In a bowl, combine cream cheese, spinach, salt and red pepper.  Stirring well to combine.  Spoon the mixture into the pockets of the chicken breasts.",
        "Melt 2 TB butter in an oven proof skillet or Dutch oven on medium heat.  Add the garlic and red pepper flakes until fragrant, about 2 minutes, stirring frequently.  Stir in last 5 ingredients.  Bring to boil, simmer for 5 minutes.  Nestle stuffed breasts into the sauce and place into the oven.  Cook for 25-30 minutes or until internal temperature reaches 165.",
      ],
      createdAt: "2023-07-26T23:12:54.395514",
      updatedAt: "2023-07-26T23:12:54.395515",
    },
    {
      title: "Double Orange Mini-Loaves",
      description: "",
      ingredients: [
        "1 \u00be cup all purpose flour",
        "2 teaspoon baking soda",
        "\u00bc teaspoon salt",
        "\u2154 cup sugar",
        "\u00bd cup canola oil",
        "1 teaspoon vanilla extract",
        "juice from 2 oranges (about \u00bd cup)",
        "zest from 2 oranges",
        "1 cup sour cream",
        "1 egg",
        "2 cups powdered sugar",
        "juice from 2 oranges (about \u00bd cup)",
        "zest from 2 oranges",
      ],
      steps: [
        "Mix dry ingredients in a large bowl (flour, sugar, and baking soda).",
        "Mix wet ingredients in a medium sized bowl (juice from 2 oranges, oil, egg, zest from 2 oranges, vanilla, and sour cream).",
        "Combine wet and dry ingredients. Mix until well combined. Divide evenly between 4 (5 inch) mini loaf pans. Fill each about \u00be full (about 1/3 cup).",
        "Bake at 350 degrees for about 22 minutes, or until a toothpick inserted comes out clean.",
        "Transfer to a cooling rack and cool completely. Store in an airtight container at room temperature.",
        "Glaze: In a medium sized mixing bowl combine all ingredients and whisk until smooth.",
        "Glaze: Dip mini loaf tops into glaze and set on a cooling rack with foil underneath to catch the drippings. Let harden for about 20 minutes and dip again if desired.",
      ],
      createdAt: "2023-07-26T23:12:54.395516",
      updatedAt: "2023-07-26T23:12:54.395517",
    },
    {
      title: "Make Ahead Gravy",
      description: "",
      ingredients: [
        "\u00bc cup butter",
        "\u00bc cup all-purpose flour",
        "2 cups stock (saved from cooking chicken for dressing)",
        "\u00bd ts rubbed sage",
        "\u00bd ts salt",
        "\u00bc ts pepper",
        "\u00bc ts dried thyme",
        "\u00bc ts garlic powder",
      ],
      steps: [
        "Melt butter in heavy medium saucepan over medium heat; whisk in flour, and cook, whisking constantly, 3-4 minutes or until mixture is light brown and smooth.",
        "Slowly whisk in 2 cups stock. Increase heat to high; bring to a boil, whisking occasionally. Reduce heat to medium; stir in spices. Simmer, stirring occasionally, 10 to 15 minutes or until desired thickness.",
        "To make ahead, cool gravy completely. Cover and chill up to 3 days. May need a bit of stock when you reheat over med-low heat until hot.",
      ],
      createdAt: "2023-07-26T23:12:54.395519",
      updatedAt: "2023-07-26T23:12:54.395520",
    },
    {
      title: "Spicy Meatballs",
      description: "",
      ingredients: [
        "1 lb ground beef",
        "1 lb ground sausage (Jimmy Dean Hot)",
        "1/2 cup Panko breadcrumbs",
        "\u00be cup minced onion",
        "4 cloves garlic, minced",
        "1 cup chopped parsley",
        "2 beaten eggs",
        "1 ts red pepper flakes",
        "1 TB Cajun seasoning",
        "2 TB Dijon mustard",
        "2 TB Worcestershire",
        "\u00bd ts salt",
        "\u00bd ts pepper",
      ],
      steps: [
        "Shape using ice cream scooper (1 \u00bd oz). Makes 28 meatballs. Coat in flour and fry in \u00bd cup olive oil. Change oil with each batch.",
      ],
      createdAt: "2023-07-26T23:12:54.395521",
      updatedAt: "2023-07-26T23:12:54.395522",
    },
    {
      title: "Turkey Carcass Soup",
      description:
        "A turkey carcass soup is the answer when you don't want to waste a single bite of turkey. This is a delicious soup and one of my favorites. If you want to freeze some, leave out the potatoes.",
      ingredients: [
        "1 tablespoon Worcestershire sauce",
        "1 large bay leaf",
        "1/4 teaspoon freshly cracked black pepper",
        "1 pinch dried thyme",
        "2 stalks celery, diced",
        "1 turkey carcass",
        "1 large onion, diced",
        "1 teaspoon dried basil",
        "6 small potatoes, diced",
        "1 1/2 teaspoons salt",
        "1/2 cup uncooked barley",
        "4 quarts water",
        "1 (28 ounce) can whole peeled tomatoes, chopped",
        "1 teaspoon dried parsley",
        "4 large carrots, diced",
        "1 1/2 cups shredded cabbage",
        "1/4 teaspoon poultry seasoning",
        "1/4 teaspoon ground paprika",
      ],
      steps: [
        "Place turkey carcass into a large soup pot; pour in water and bring to a boil over medium heat. Reduce heat to a simmer, and cook until the remaining meat falls off the bones, about 1 hour.",
        "Remove turkey carcass from the pot. Remove and chop any remaining turkey meat. Discard carcass.",
        "Strain broth through a fine mesh strainer into a clean soup pot. Add chopped turkey to the strained broth and bring to a boil.",
        "Reduce heat and stir in tomatoes, potatoes, carrots, onion, celery, cabbage, barley, Worcestershire sauce, salt, parsley, basil, bay leaf, pepper, paprika, poultry seasoning, and thyme. Simmer until vegetables are tender, about 1 more hour.",
        "Remove bay leaf before serving.",
      ],
      createdAt: "2023-07-26T23:12:54.395523",
      updatedAt: "2023-07-26T23:12:54.395524",
    },
    {
      title: "Instant Pot Beef Stew",
      description:
        "I replace the olive oil with butter I toss the beef with about a tablespoon of flour, the salt, pepper and Italian seasoning I replace about a cup of the beef broth Cabernet Sauvignon (anywhere from a half to a whole cup, but the total liquid is 2.5 cups) I add some celery",
      ingredients: [
        "1 \u00bd Pounds Beef Stew Meat",
        "1 Tablespoon Olive Oil",
        "1 Teaspoon Salt",
        "1 Teaspoon Pepper",
        "1 Teaspoon Italian Seasoning",
        "2 Tablespoons Worcestershire Sauce",
        "3 Cloves Garlic, Minced",
        "1 Large Onion, Chopped",
        "1 16 Ounce Bag Baby Carrots, Cut Into Slices",
        "1 Pound Potatoes, Cubed",
        "2 \u00bd Cups Beef Broth",
        "1 10 Ounce Can Tomato Sauce",
        "2 Tablespoons Cornstarch",
        "2 Tablespoons Water",
      ],
      steps: [
        "Add the olive oil to the instant pot and turn on the saute function. When the oil starts to sizzle add the meat and season with the salt, pepper, and Italian seasoning.",
        "Cook the meat until Browned on all sides.",
        "Add the beef broth to the instant pot and use a spoon to scrape the brown bits from the bottom of the pan.",
        "Add the Worcestershire sauce, garlic, onion, carrots, potatoes, and tomato sauce.",
        "Close the lid and steam valve on the instant pot.",
        "Cook on high pressure for 35 minutes, then allow the pressure to release naturally for 10 minutes before doing a quick release.",
        "Mix together the cornstarch and cold water in a small bowl and stir into the stew until thickened.",
      ],
      createdAt: "2023-07-26T23:12:54.395526",
      updatedAt: "2023-07-26T23:12:54.395527",
    },
    {
      title: "Chocolate Chipotle Cupcakes or Mini Loaves",
      description:
        "Double recipe for 18 mini loave pan \u2013 makes 22 OR Single recipe makes 18 small cupcakes (use scant \u00bc cup)",
      ingredients: [
        "1 1/2 sticks (3/4 cup) unsalted butter, cut into pieces",
        "1/2 cup freshly brewed coffee",
        "1/2 cup unsweetened Dutch-process cocoa",
        "1/4 cup milk",
        "1 1/2 cups all-purpose flour",
        "1 1/2 cups granulated sugar",
        "1 teaspoon cinnamon",
        "1/2 teaspoon chipotle chile powder",
        "1/2 teaspoon baking soda",
        "1/4 teaspoon baking powder",
        "1/4 teaspoon fine salt",
        "1/3 cup sour cream",
        "2 large eggs, at room temperature",
        "1 teaspoon pure vanilla extract",
        "Confectioners' sugar, for dusting",
      ],
      steps: [
        "Position the rack in the center of the oven and preheat to 350\u00b0F. Generously spray the inside of a mini-loaf baking pan with the cooking spray and set aside. For cupcakes, line muffin tin with paper cups.",
        "Put the butter, coffee, cocoa and milk in a small microwave-safe bowl, cover with plastic wrap and microwave on high until the butter melts, about 3 minutes. Whisk to combine.",
        "Whisk the flour, granulated sugar, cinnamon, chile powder, baking soda, baking powder and salt in a large bowl. Beat the sour cream, eggs and vanilla in a small bowl. Whisk the hot cocoa mixture into the dry ingredients; stir in the sour cream mixture, until just combined. Divide the batter equally among the loaves, filling each about \u00be of the way. Use 1/3 cup batter per loaf. Makes 11.",
        "Bake until a toothpick inserted in the center comes out clean, about 22 minutes. Small cupcakes about 18 minutes. Allow the loaves to cool in the pan on a rack for 10 minutes. Run a knife around each loaf to loosen, remove the loaves and let cool completely on a rack.",
        "To serve, dust the tops of the loaves with confectioners' sugar. If you like, cut out small hearts or other festive stencils and place them on the loaves before dusting.",
      ],
      createdAt: "2023-07-26T23:12:54.395528",
      updatedAt: "2023-07-26T23:12:54.395529",
    },
    {
      title: "Blueberry Sauce",
      description: "",
      ingredients: [
        "1 \u00bd cups sugar",
        "1 \u00bd cups water",
        "\u00bd cup fresh squeezed orange juice",
        "3 TB cornstarch",
        "1 \u00bd ts orange zest",
        "1 \u00bd cups blueberries, picked over and rinsed",
        "1 \u00bd TB unsalted butter",
      ],
      steps: [
        "This can be made in advance and kept refrigerated for up to a week and re-warmed just before serving. Try on plain pancakes or waffles or ice cream.",
        "In a small saucepan over medium-high heat, stir together the sugar, water, orange juice, cornstarch, and orange zest. Cook, stirring occasionally, until thickened, about 5 minutes. Stir in the blueberries and simmer the mixture, stirring occasionally, until berries have burst, about 5 minutes. Add the butter and stir until melted. Remove from heat and spoon or ladle over warm \u2018French Toast\u2019.",
      ],
      createdAt: "2023-07-26T23:12:54.395530",
      updatedAt: "2023-07-26T23:12:54.395531",
    },
    {
      title: "Stuffed Grape Leaves",
      description: "",
      ingredients: [
        "1.5 lb ground lamb (use \u00bd lb with onions & garlic for puff pastry)",
        "1 small onion, finely diced",
        "4 cloves garlic, minced",
        "\u00bc ts cayenne pepper",
        "14 oz can diced canned tomatoes with liquid",
        "\u00bd cup white rice",
        "\u00be cup chicken broth",
        "3 ts red wine vinegar",
        "\u00bc ts cinnamon",
        "\u00bd cup loosely packed cilantro, chopped",
        "1 \u00bd ts salt",
        "Pepper and hot sauce to taste",
        "1 jar grape leaves",
        "Another 1 \u00bd cup chicken broth to cover",
      ],
      steps: [
        "Brown lamb with onions and garlic.  Save 1/3 of it for puffed pastry. Add other ingredients.  Cover and simmer for 15 minutes or so until rice is done.",
        "Cool mixture.",
        "Spray 13 x 9 pan.  Fill grape leaves with 1 TB mixture and place in rows in pan, cover halfway with chicken broth.  Bake at 350 degrees for 30 minutes.",
      ],
      createdAt: "2023-07-26T23:12:54.395532",
      updatedAt: "2023-07-26T23:12:54.395533",
    },
    {
      title: "Quick Chicken and Sausage Jambalaya",
      description: "",
      ingredients: [
        "1 TB canola oil",
        "2 to 2.5 lbs boneless, skinless chicken breast, cut into 1\u201d bitesize pieces",
        "12 oz Hillshire Farms Beef Sausage, sliced in bite sized pieces",
        "1 large white onion, chopped (about 1 \u00bd cups)",
        "1 large green pepper, chopped (about 1 \u00bd cups)",
        "1 cup chopped celery",
        "3 garlic cloves, minced",
        "2 bay leaves",
        "1 TB Creole seasoning",
        "1 ts dried thyme",
        "1 ts dried oregano",
        "3 cups chicken broth",
        "2 (14.5 oz) cans diced fire-roasted tomatoes",
        "Cooked rice (about 3 cups, personal liking)",
      ],
      steps: [
        "Heat oil in Dutch oven over medium high.  Add chicken and sausage, and cook, stirring frequently, until browned on all sides, 8 to 10 minutes.  Remove with a slotted spoon to paper towels.",
        "Add onion, green pepper, celery, bay leaves, Creole seasoning, thyme, and oregano to hot drippings.  Cook over med-high heat until veggies are tender, 5 to 7 minutes, adding the garlic the last minute or two.",
        "Stir in chicken and sausage, chicken broth and tomatoes.  Bring to a boil, cover and reduce heat to a simmer, stirring occasionally for 15 to 20 minutes.  Serve over cooked rice.",
      ],
      createdAt: "2023-07-26T23:12:54.395537",
      updatedAt: "2023-07-26T23:12:54.395538",
    },
    {
      title: "Ginger Party Nuts",
      description: "",
      ingredients: [
        "\u00bc cup Ginger Syrup",
        "1 lb (4 cups) unsalted mixed nuts",
        "\u00bd cup Crystallized Ginger, coarsely chopped",
        "\u00bc ts cayenne pepper",
        "2 ts coarse salt",
        "\u00bc ts black pepper",
        "3 TB sesame seeds",
      ],
      steps: [
        "Preheat oven to 350.",
        "In a medium saucepan, add ginger syrup.",
        "Heat on medium until just warm.  Add remaining ingredients, mix well.  Line baking sheet with parchment paper.  Arrange nut mixture in a single layer on sheet.",
        "Bake 15 minutes or until nuts are golden, stirring occasionally.",
        "Cool completely, then break into bite-size pieces. Store in an airtight container.",
      ],
      createdAt: "2023-07-26T23:12:54.395539",
      updatedAt: "2023-07-26T23:12:54.395540",
    },
    {
      title: "Tzatziki Sauce (Yogurt and Cucumber Sauce)",
      description: "",
      ingredients: [
        "Long English Cucumber, scrape out middle, then grate",
        "Salt for cucumbers \u2013 1 \u2013 2 ts",
        "2 (5.3 oz) containers plain Greek yogurt",
        "2 cloves garlic, finely minced",
        "1 TB fresh lemon juice",
        "1 ts red wine vinegar",
        "1 ts EVOO",
        "Squart of Chalula",
        "\u00bc cup chopped mint or dill or parsley or mixture",
        "\u00bc ts black pepper",
      ],
      steps: [
        "Place the grated cucumber in a colander and sprinkle with salt, mixing so all the cucumber pieces are coated. Place the colander over a bowl so the salt can draw the moisture out of the cucumber. Allow the cucumber to drain for 15-30 minutes.",
        "Combine the other ingredients in a medium mixing bowl.",
        "Press and squeeze the cucumber with your hands until you have pressed out as much water as possible.  Wring out in paper towels to get more water out.",
        "Stir the cucumber into the yogurt mixture. Taste and add more salt, pepper, vinegar, garlic or herbs if you like.",
        "Tzatziki tastes best if allowed to chill in the refrigerator for at least an hour.",
      ],
      createdAt: "2023-07-26T23:12:54.395541",
      updatedAt: "2023-07-26T23:12:54.395542",
    },
    {
      title: "Queso with Chorizo",
      description:
        "This is very tasty, but it makes a lot.  12 servings.  Could easily be halved by using 2 poblanos and 2 tomatoes and halving the rest of ingredients.",
      ingredients: [
        "3 large poblano chilis",
        "1 lb Mexican chorizo, casings removed",
        "1 medium white onion, chopped",
        "3 ripe plum tomatoes, chopped",
        "\u00bd cup whole milk",
        "\u00bd cup heavy whipping cream",
        "4 oz cream cheese",
        "2 lb American cheese, chopped",
        "Cholula to taste (optional)",
        "Tortilla Chips",
      ],
      steps: [
        "Preheat oven to broil with oven rack 6 inches from heat.  Place poblanos on baking sheet, and broil until skin is charred and blistered, about 5 minutes per side.  Transfer to medium bowl and cover tightly with plastic wrap; let stand 10 minutes.",
        "Uncover bowl, and peel poblanos.  Cut in half lengthwise and remove and discard stems and seeds.  Chop poblanos.",
        "Cook chorizo in a large skillet over medium-high heat, stirring occasionally to break into smaller pieces, until brown and crisp, 6 to 8 minutes.  Remove chorizo with slotted spoon and set aside.",
        "Reduce heat to medium.  Add onion to drippings for 3-4 minutes.  Add chopped poblanos and tomatoes, and cook until softened, about 2 minutes.  Stir in milk, whipping cream, cream cheese and American cheese, stirring and scraping skillet.  Add Cholula to taste, if desired.  Simmer, stirring constantly, until thoroughly melted and combined, about 1 minute.  Remove from heat.  Scrape queso in bowl or serve from pan, and garnish with cooked chorizo.  Serve with tortilla chips.",
      ],
      createdAt: "2023-07-26T23:12:54.395543",
      updatedAt: "2023-07-26T23:12:54.395544",
    },
    {
      title: "Baked Ham and Cheese Party Sandwiches",
      description: "",
      ingredients: [
        "\u00bd cup melted butter",
        "2 TB Dijon mustard",
        "1 TB Worcestershire sauce",
        "1 TB sesame seeds or poppy seeds",
        "1 tablespoon dried minced onion",
        "12 to 24 mini sandwich rolls (enough to fill a 13x9 pan)",
        "1 pound thinly sliced cooked deli ham (could add salami)",
        "1 pound thinly sliced Swiss cheese (or other kind)",
      ],
      steps: [
        "Preheat oven to 350 degrees F. Spray a 9x13-inch baking dish.",
        "In a bowl, mix together butter, Dijon mustard, Worcestershire sauce, poppy seeds, and dried onion. Separate the tops from bottoms of the rolls, and place the bottom pieces into the prepared baking dish. Arrange the meat & cheese on bottom of roll, and top with remaining ham slices in a layer. Place the tops of the rolls onto the sandwiches. Pour the mustard mixture evenly over the rolls.",
        "Bake in the preheated oven until the rolls are lightly browned and the cheese has melted, about 20 minutes. Bake 10 minutes loosely covered, 10 minutes uncovered.",
      ],
      createdAt: "2023-07-26T23:12:54.395546",
      updatedAt: "2023-07-26T23:12:54.395547",
    },
    {
      title: "Apple Topping w/Cinnamon Whipped Cream",
      description: "",
      ingredients: [
        "2 TB butter",
        "4 lg apples, sliced",
        "2 TB sugar",
        "\u00bd ts cinnamon",
        "1/8 ts nutmeg",
        "\u00bd ts lemon juice \u2013 fresh is best",
        "1 cup heavy whipped cream",
        "1 TB confectioners\u2019 sugar",
        "1 TB brown sugar",
        "\u00bd ts cinnamon",
      ],
      steps: [
        "In large skillet, saut\u00e9 apples\u2019 with all other ingredients until soft (about 10 minutes).",
        "Meanwhile, beat whipped cream and 3 other ingredients until stiff peaks.",
      ],
      createdAt: "2023-07-26T23:12:54.395548",
      updatedAt: "2023-07-26T23:12:54.395549",
    },
    {
      title: "Wild and Brown Rice with Mushrooms",
      description: "",
      ingredients: [
        "3 tablespoons unsalted butter",
        "1/2 medium onion, diced",
        "1 cup brown rice",
        "4 oz wild rice (1 small Reese\u2019s pkg)",
        "4 1/2 cups chicken broth",
        "1 tablespoon olive oil",
        "8 ounces white button mushrooms, sliced",
        "8 ounces shiitake mushrooms, sliced with tough stems removed",
        "2 teaspoons fresh thyme leaves",
        "2 cloves garlic, minced",
        "Kosher salt and freshly ground black pepper",
        "1 tablespoon chopped fresh parsley",
      ],
      steps: [
        "Heat 2 tablespoons of the butter in a large saucepot over medium heat. Add the onion and saute until translucent, about 5-7 minutes. Add the wild rice only and toast while stirring until it begins to smell nutty, about 1 minute. Add the chicken stock and bring to a boil, then reduce to a simmer, cover and cook on low for about 10 minutes.   Then add the brown rice and simmer until the water is absorbed, about 40-45 minutes.",
        "While the rice is cooking, heat the remaining 1 tablespoon butter along with the oil in a large skillet over medium-high heat. Add the button mushrooms, shiitake mushrooms and thyme and cook, stirring often until they begin to brown, about 10 minutes. Add the garlic, season with salt and pepper and cook until the garlic is fragrant, about 1 minute more.",
        "When the rice is cooked, fluff with a fork and gently fold in the mushrooms. Add to a serving bowl and sprinkle with the parsley before serving.",
      ],
      createdAt: "2023-07-26T23:12:54.395550",
      updatedAt: "2023-07-26T23:12:54.395551",
    },
    {
      title: "Greek Puff Pastry Appetizers with Kalamata Olives",
      description: "",
      ingredients: [
        "\u00bd lb lamb mixture from stuffed grape leaves recipes",
        "1 pkg (10 oz) frozen chopped spinach",
        "1/2 cup chopped fresh red bell pepper",
        "1 ts oregano",
        "\u00bc ts black pepper",
        "\u00bc ts salt",
        "2/3 cup feta cheese, crumbled",
        "1 teaspoon lemon juice",
        "2 eggs, separated",
        "1 package thawed Puff Pastry Shells",
        "1/3 cup chopped Lindsay Greek Kalamata Olives",
      ],
      steps: [
        "Preheat oven to 400 degrees F. Prepare a baking sheet by lining it with parchment paper.",
        "Beat 1 egg with 1 TB water in small bowl.  Set aside.",
        "Wring out thawed spinach and put in medium bowl.  Add all other ingredients, except olives.",
        "Separate mixture in 2 parts, 12 oz and 8 oz.  Add the olives to the 8 oz bowl.",
        "Unfold 1 pastry sheet on lightly floured surface.  Roll into a 12 \u201c square.  Cut into 16 (3\u201d) squares.  Repeat with other sheet when needed.32 total.",
        "Place 1 full TB of mixture in center.  Brush edges with egg mixture.  Fold the pastry over to form triangles.  Crimp the edges with a fork to seal.  Place on baking sheet and brush with egg mixture.",
        "The 12 oz bowl made about 19.  The 8 oz bowl around 13. 32 total.",
        "Bake for about 15-20 minutes or until golden brown.  Let cool on pan on wire rack for 10 minutes.",
      ],
      createdAt: "2023-07-26T23:12:54.395552",
      updatedAt: "2023-07-26T23:12:54.395553",
    },
    {
      title: "Wedding Cookies",
      description: "",
      ingredients: [
        "1 \u00bd cups unsalted butter",
        "3/4 cups confectioners sugar",
        "3/4 ts salt",
        "1 1/2 cups finely ground almonds",
        "3 ts vanilla extract",
        "2 ts almond extract",
        "3 cups sifted all-purpose flour",
        "additional powdered sugar or dutch anise powder for rolling",
      ],
      steps: [
        "Preheat oven to 325 degrees F.",
        "Cream butter in a bowl, gradually add confectioners sugar and salt. Beat until light and fluffy. Add almonds and extracts. Blend in flour gradually and mix well.",
        "Shape into balls using a scant TB for each cookie. Place on ungreased cookie sheets and bake for 17-20 minutes (depending on size). Do not brown. Cool slightly, then roll in the extra sugar.",
      ],
      createdAt: "2023-07-26T23:12:54.395555",
      updatedAt: "2023-07-26T23:12:54.395555",
    },
    {
      title: "Funfetti Cake Frosting",
      description: "",
      ingredients: [
        "1 1/4 (2 \u00bd sticks) cups unsalted butter, at room temperature",
        "4 cups powdered sugar",
        "\u215b teaspoon kosher salt",
        "1 ts clear imitation vanilla",
        "1/2 ts almond extract",
        "1 tablespoons whole milk",
      ],
      steps: [
        "In a standing mixer fitted with a paddle attachment, beat the butter until smooth and gradually beat in the powdered sugar. Add the salt, extracts, and milk and beat to combine.",
      ],
      createdAt: "2023-07-26T23:12:54.395557",
      updatedAt: "2023-07-26T23:12:54.395558",
    },
    {
      title: "Ginger Sauce",
      description:
        "This can be made in advance and kept refrigerated for up to a week and re-warmed just before serving. Try on plain pancakes or waffles or ice cream.",
      ingredients: [
        "Zest of 1 lemon",
        "1/8 cup lemon juice = juice of 1 lemon",
        "\u00be cup water",
        "\u00be cup sugar",
        "4 ts corn starch",
        "2 TB of syrup from jar of ginger balls",
        "3 balls stem ginger in syrup, chopped",
        "\u00bd cup chopped candied ginge",
      ],
      steps: [
        "In a small saucepan over medium-high heat, stir together all ingredients except last 2 (ginger). Cook, stirring occasionally, until thickened, about 5 minutes. Stir in the 2 kinds of ginger, stirring occasionally, about 5 minutes. Remove from heat.",
      ],
      createdAt: "2023-07-26T23:12:54.395559",
      updatedAt: "2023-07-26T23:12:54.395560",
    },
    {
      title: "Banana Chocolate Chip Muffins",
      description: "",
      ingredients: [
        "1 \u00bd cups all purpose flour",
        "2/3 cup sugar",
        "1 \u00bd ts baking powder",
        "\u00bc ts salt",
        "1 cup mashed ripe bananas (about 2 large)",
        "1 large egg",
        "\u00bd cup (1 stick) butter, melted \u00bc cup milk",
        "\u00be cup semisweet chocolate chips",
      ],
      steps: [
        "Preheat oven to 350. Line 12 1/3 cup muffin cups with liners. Mix flour, sugar, baking powder and salt in large bowl. Mix mashed bananas, egg, melted butter and milk in medium bowl. Stir banana mixture into dry ingredients just until blended. Stir in chocolate chips.",
        "Divide batter among prepared muffin cups, filling each about \u00be full. Bake muffins until tops are pale golden and tester inserted into center comes out with some melted chocolate attached but no crumbs, about 32 minutes. (more like 23 in my oven)",
      ],
      createdAt: "2023-07-26T23:12:54.395561",
      updatedAt: "2023-07-26T23:12:54.395562",
    },
    {
      title: "Chocolate Chip Cake",
      description: "",
      ingredients: [
        "2 cups all-purpose flour",
        "1 \u00bd cups sugar",
        "2 ts baking powder",
        "\u00bd ts soda",
        "\u00bd ts salt",
        "1 1/3 cups sour cream",
        "2/3 cup butter, softened",
        "1 ts vanilla extract",
        "3 eggs",
        "\u00bd cup sugar",
        "1 ts cinnamon",
        "6-oz pkg (1 cup) semi-sweet choc chips",
      ],
      steps: [
        "Preheat oven to 350. Grease 13x9 inch pan.",
        "In large bowl, combine flour, baking soda, and salt; set aside. In large mixer bowl, blend 1st 9 ingredients at low speed until moistened. Beat 3 minutes at medium speed. Pour half of batter (2 \u00bd cups) into prepared pan.",
        "In small bowl, combine \u00bd cup sugar with cinnamon. Sprinkle half of this mixture and half of choc chips over batter.",
        "Repeat with remaining batter, sugar mixture and choc chips.",
        "Bake at 350 for 35-40 minutes or until toothpick inserted comes out clean.",
      ],
      createdAt: "2023-07-26T23:12:54.395563",
      updatedAt: "2023-07-26T23:12:54.395564",
    },
    {
      title: "Mexican Chopped Salad",
      description: "",
      ingredients: [
        "(Dressing) \u00bc cup fresh lime juice",
        "(Dressing) 2 tablespoons honey",
        "(Dressing) \u00bd teaspoon cumin",
        "(Dressing) 1 clove garlic finely minced",
        "(Dressing) \u00bd teaspoon salt",
        "(Dressing) 2 tablespoons canola oil",
        "(Dressing) 2 tablespoons extra virgin olive oil",
        "(Dressing) freshly ground black pepper",
        "(Dressing) taste and add salt if needed",
        "(Tortilla Strips) 6 6- inch corn tortillas",
        "(Tortilla Strips) 1 \u00bd tablespoons canola oil",
        "(Tortilla Strips) \u00bd teaspoon sea salt",
        "(Salad) 1 medium head romaine lettuce chopped in approximately \u00bd inch pieces",
        "(Salad) 1 medium bell pepper diced in \u00bc-inch pieces**, any color (I used orange)",
        "(Salad) \u00bd medium red onion diced in \u00bc-inch pieces**",
        "(Salad) \u00bd medium jicama peeled and diced in \u00bc-inch pieces**",
        "(Salad) 1 medium zucchini diced in \u00bc-inch dice**",
        "(Salad) 4 medium tomatoes seeded and diced into \u00bc-inch dice**",
        "(Salad) 4 ears corn if fresh corn or 1 \u00bd cups of sweet, tiny frozen corn",
        "(Salad) 1 1/2 cups canned black beans drained and rinsed",
        "(Salad) 1/2 cup finely chopped cilantro plus whole cilantro leaves for garnish, if desired",
      ],
      steps: [
        "For the dressing, combine lime juice, honey, cumin garlic and salt.",
        "In a slow, steady stream, add the oils, stirring continuously with a fork or small whisk.  Taste and add more salt and pepper, if needed. Set aside.",
        "For the corn tortilla strips, preheat oven to 400\u02daF.",
        "Stack corn tortillas on a cutting board. Cut in half. Cut each stack of halves into thin strips, widthwise, about \u00bc-inch thick.",
        "Transfer tortilla strips to a sheet pan. Drizzle with oil. Sprinkle with salt and toss.",
        "Bake for 15-20 minutes, stirring every 5 minutes, or until light golden brown, cool.",
        "For the salad, place corn, two ears at a time, in the microwave and cook for 3 \u00bd minutes.",
        "Remove from microwave with a hot pad and allow to cool for 5 minutes.",
        "After cooling, cut bottom end of corn off, about 1 \u00bd inches from end. Pull back husk and silks (almost all of the silk should easily pull away). Cut kernels from husks and set aside.",
        "Combine corn and other salad ingredients in a large bowl. Stir to combine. Add dressing and stir to coat all ingredients. Garnish with cilantro leaves, if desired.",
        "Serve with tortilla strips on top or place a bowl on the side and let guests help themselves.",
      ],
      createdAt: "2023-07-26T23:12:54.395566",
      updatedAt: "2023-07-26T23:12:54.395567",
    },
    {
      title: "Hash Browns",
      description: "",
      ingredients: [
        "2 medium russet potatoes, shredded",
        "\u00bd medium onion, finely chopped",
        "\u00bc cup all-purpose flour",
        "1 egg",
        "Olive oil for frying",
        "1 ts salt",
        "\u00bd ts pepper",
        "\u00bd ts garlic powder",
      ],
      steps: [
        "Rinse shredded potatoes until water is clear, then drain and squeeze dry. You can squeeze them out in a tea towel. Place shreds in a bowl, and mix in the onion, flour, egg and seasonings until evenly distributed",
        "Coat the bottom of a large heavy skillet with oil over medium-high heat. When oil is sizzling hot, place potatoes into the pan in a 1/3 \u201c thick layer. Cover the whole bottom of the pan or make separate piles like pancakes. This makes 6 2 \u00bd to 3 \u201c diameter pancakes. Cook until nicely browned on the bottom, then flip over and brown on the other side. It should take at least 5-8 minutes per side. If you are cooking them in one big piece, it can be cut into quarters for easier flipping.",
      ],
      createdAt: "2023-07-26T23:12:54.395568",
      updatedAt: "2023-07-26T23:12:54.395569",
    },
    {
      title: "Empanadas",
      description:
        "This makes 4 cups of Empanada filler mixture.  Using 1 pkg Puff Pastry sheets, I had 1 \u00bc cup mixture left.  Quesadilla, nachos, omelet later?",
      ingredients: [
        "1 lb ground beef (90% lean)",
        "Small onion or shallot, minced (1/2 to \u00be cup)",
        "2 cloves garlic, minced",
        "14.5 oz crushed tomatoes",
        "\u00be cup small cubed potato, uncooked (about \u00bd a lg russet)",
        "3 TB raisons",
        "1 1/2 ts cumin",
        "1/2  ts chili powder",
        "1 ts cinnamon",
        "1 ts salt",
        "1 ts pepper",
        "2 shakes Chalula",
        "1 cup frozen peas and carrots, thawed",
        "1 pkg Puff Pastry Sheets, thawed",
      ],
      steps: [
        "Preheat 400.",
        "Brown ground with onions and garlic in last 2 minutes. Drain fat off if necessary.",
        "Add rest of ingredients except peas and carrots.  Simmer covered 15 minutes.  Add peas and carrots until heated through.",
        "Unfold 1 pastry sheet on lightly floured surface.  Roll into a 12 \u201c square.  Cut into 16 (3\u201d) squares.  Repeat with other sheet when needed.  32 total.",
        "Place 1 full TB of mixture in center.  Brush edges with egg mixture.  Fold the pastry over to form triangles.  Crimp the edges with a fork to seal.  Place on baking sheet and brush with egg mixture.",
        "Bake for about 15-20 minutes or until golden brown.  Let cool on pan on wire rack for 10 minutes.",
      ],
      createdAt: "2023-07-26T23:12:54.395570",
      updatedAt: "2023-07-26T23:12:54.395571",
    },
    {
      title: "Carrot Cake",
      description: "",
      ingredients: [
        "2 cups all-purpose flour",
        "2 cups sugar",
        "\u00bd ts salt",
        "1 ts baking soda",
        "2 ts ground cinnamon",
        "3 eggs",
        "1 and \u00bd cups veg. oil",
        "2 cups finely grated carrots",
        "1 ts vanilla extract",
        "1 cup well-drained crushed pineapple",
        "1 cup shredded coconut",
        "1 cup chopped nuts, divided",
      ],
      steps: [
        "In a mixing bowl, combine dry ingredients.",
        "Add eggs, oil, carrots and vanilla: beat until combined. Stir in pineapple, coconut, and \u00bd cup nuts.",
        "Pour unto greased 13x9x2 baking pan. Bake at 350 degrees for 50-60 minutes or until cake tests done. Cool.",
        "Combine frosting ingredients in a small bowl; mix until well blended.",
        "Frost cooled cake. Sprinkle with remaining nuts. Store in frig.",
      ],
      createdAt: "2023-07-26T23:12:54.395572",
      updatedAt: "2023-07-26T23:12:54.395573",
    },
    {
      title: "Chocolate Cookies",
      description: "",
      ingredients: [
        "2 \u00bc cups all-purpose flour",
        "2/3 cup cocoa",
        "1 ts baking soda",
        "\u00bc ts salt",
        "1 cup (2 sticks butter), softened \u00be cup granulated sugar 2/3 cup packed brown sugar",
        "1 ts vanilla extract",
        "2 Ig eggs",
        "2 cups (12 oz pkg) any kind of choc",
      ],
      steps: [
        "PREHEAT oven to 350\u00b0 F.",
        "COMBINE flour, cocoa, baking soda and salt in small bowl.",
        "Beat butter, granulated sugar, brown sugar and vanilla extract in large mixer bowl until creamy. Add eggs, one at a time, beating well after each addition. Gradually beat in flour mixture. Stir in morsels. Drop by well-rounded teaspoon onto ungreased baking sheets.",
        "BAKE for 9 to 11 minutes or until centers are set. Cool on baking sheets for 2 minutes; remove to wire racks to cool completely.",
      ],
      createdAt: "2023-07-26T23:12:54.395574",
      updatedAt: "2023-07-26T23:12:54.395575",
    },
    {
      title: "Smokey Garlic Ketchup Sauce",
      description: "",
      ingredients: [
        "1 cup Ketchup",
        "\u00be cup packed brown sugar",
        "\u00bc cup minced onion",
        "1 clove garlic, minced",
        "1 ts liquid smoke",
        "\u00bc ts garlic powder",
        "\u00bd ts chalula",
        "1/8 ts cloves",
      ],
      steps: ["Make Sauce"],
      createdAt: "2023-07-26T23:12:54.395577",
      updatedAt: "2023-07-26T23:12:54.395578",
    },
    {
      title: "Blueberry French Toast",
      description: "",
      ingredients: [
        "1 TB unsalted butter",
        "14 slices home-style white bread, crusts discarded and bread cut into 1 inch pieces",
        "2 (8-ounce) pkgs cold cream cheese, cut into 1 inch cubes",
        "1 cup blueberries, picked over and rinsed",
        "10 large eggs",
        "2 cups half and half",
        "1/3 cup maple syrup",
        "\u00bc cup fresh squeezed orange juice",
      ],
      steps: [
        "Butter a 9 x 13 baking dish with a TB of butter. Arrange half of the bread cubes on the bottom of the baking dish. Top the bread cubes with the cream cheese cubes and blueberries and arrange the remaining bread cubes over the blueberries. In a large bowl whisk together the eggs, half and half, syrup, and orange juice. Pour the egg mixture evenly over the bread mixture. Cover with aluminum foil and refrigerate for at least 1 hour and up to overnight.",
        "Remove the baking dish from the refrigerator and allow to come to room temperature for about 20 minutes. Position rack in center of oven and preheat to 350 degrees.",
        "Bake the \u2018French Toast\u2019 with foil cover for 30 minutes. Remove foil and bake for another 30 minutes or until golden brown and puffed. Allow dish to cool for 15 minutes. Serve with blueberry sauce ladles over the top.",
      ],
      createdAt: "2023-07-26T23:12:54.395580",
      updatedAt: "2023-07-26T23:12:54.395581",
    },
    {
      title: "It's-a-good-morning Muffins",
      description: "Yield: about 18 Muffins",
      ingredients: [
        "2 cups all-purpose flour",
        "1 cup sugar",
        "2 ts baking soda",
        "2 ts ground cinnamon",
        "\u00bd ts salt",
        "2 cups grated carrots",
        "\u00bc cup golden raisins",
        "\u00bc cup dark raisins",
        "\u00bd cup chopped pecans",
        "\u00bd cup shredded coconut",
        "1 Granny Smith apple, peeled, cored and chopped, then squeeze out liquid by hand",
        "2 large eggs",
        "1 cup veg oil",
        "2 ts vanilla extract",
      ],
      steps: [
        "Position rack in center of oven and preheat oven to 350 degrees. If not using muffin tins, then generously grease muffin pan ans set aside.",
        "Sift first five ingredients. Stir in next 6 ingredients. In another bowl, combine last 3 ingredients. Add wet mixture to flour mixture just until combined. Spoon into pan.",
        "Bake until muffins spring back to the touch and are golden brown, about 25 to 30 minutes. Really matters on the oven.",
      ],
      createdAt: "2023-07-26T23:12:54.395583",
      updatedAt: "2023-07-26T23:12:54.395584",
    },
  ];

  console.log("Seed starting ...");

  recipesData.forEach(async (recipe) => {
    const recipeInsert = {
      title: recipe["title"],
      description: recipe["description"],
      slug: createSlug(recipe["title"]),
    };

    const recipeId = await createRecipe(recipeInsert);

    if (recipeId === undefined) return null;

    const insertRecipeSteps = recipe["steps"].map(
      (step: string, idx: number): InsertRecipeStepSchema => {
        return {
          recipeId,
          step,
          stepNumber: idx + 1,
        };
      },
    );

    await createRecipeSteps(insertRecipeSteps);

    const insertRecipeIngredients = recipe["ingredients"].map(
      (ingredient: string): InsertRecipeIngredientSchema => {
        return {
          recipeId,
          ingredient,
        };
      },
    );

    await createRecipeIngredients(insertRecipeIngredients);

    console.log("Seed finished.");
  });
})();
